/*
 * Copyright (c) Velocity BPA, LLC
 * Licensed under the Business Source License 1.1
 * Commercial use requires a separate commercial license.
 * See LICENSE file for details.
 */

import type { INodeProperties } from 'n8n-workflow';

export const checkoutOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['checkout'] } },
		options: [
			{ name: 'Create Payment', value: 'createPayment', description: 'Initiate a payment', action: 'Create a payment' },
			{ name: 'Create Session', value: 'createSession', description: 'Create a payment session for Drop-in/Components', action: 'Create a session' },
			{ name: 'Get Card Details', value: 'getCardDetails', description: 'Get card brand and details from BIN', action: 'Get card details' },
			{ name: 'Get Payment Methods', value: 'getPaymentMethods', description: 'Get available payment methods', action: 'Get payment methods' },
			{ name: 'Get Session', value: 'getSession', description: 'Get session result', action: 'Get a session' },
			{ name: 'Submit Details', value: 'submitDetails', description: 'Submit additional payment details', action: 'Submit payment details' },
		],
		default: 'createSession',
	},
];

export const checkoutFields: INodeProperties[] = [
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		required: true,
		default: 0,
		description: 'The payment amount in major units (e.g., 10.00 for $10)',
		displayOptions: { show: { resource: ['checkout'], operation: ['createSession', 'createPayment'] } },
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		required: true,
		default: 'USD',
		description: 'The three-character ISO currency code',
		displayOptions: { show: { resource: ['checkout'], operation: ['createSession', 'createPayment', 'getPaymentMethods'] } },
	},
	{
		displayName: 'Reference',
		name: 'reference',
		type: 'string',
		required: true,
		default: '',
		description: 'Your unique reference for this payment',
		displayOptions: { show: { resource: ['checkout'], operation: ['createSession', 'createPayment'] } },
	},
	{
		displayName: 'Return URL',
		name: 'returnUrl',
		type: 'string',
		required: true,
		default: '',
		description: 'URL to redirect the shopper after payment',
		displayOptions: { show: { resource: ['checkout'], operation: ['createSession', 'createPayment'] } },
	},
	{
		displayName: 'Session ID',
		name: 'sessionId',
		type: 'string',
		required: true,
		default: '',
		description: 'The unique identifier of the session',
		displayOptions: { show: { resource: ['checkout'], operation: ['getSession'] } },
	},
	{
		displayName: 'Session Result',
		name: 'sessionResult',
		type: 'string',
		required: false,
		default: '',
		description: 'The session result returned from the frontend',
		displayOptions: { show: { resource: ['checkout'], operation: ['getSession'] } },
	},
	{
		displayName: 'Card Number (First 6 Digits)',
		name: 'cardNumber',
		type: 'string',
		required: true,
		default: '',
		description: 'The first 6 digits of the card number (BIN)',
		displayOptions: { show: { resource: ['checkout'], operation: ['getCardDetails'] } },
	},
	{
		displayName: 'Payment Method Type',
		name: 'paymentMethodType',
		type: 'options',
		required: true,
		default: 'scheme',
		description: 'The type of payment method',
		options: [
			{ name: 'Card (scheme)', value: 'scheme' },
			{ name: 'Apple Pay', value: 'applepay' },
			{ name: 'Google Pay', value: 'googlepay' },
			{ name: 'PayPal', value: 'paypal' },
			{ name: 'iDEAL', value: 'ideal' },
			{ name: 'Stored Payment Method', value: 'storedPaymentMethod' },
		],
		displayOptions: { show: { resource: ['checkout'], operation: ['createPayment'] } },
	},
	{
		displayName: 'Encrypted Card Number',
		name: 'encryptedCardNumber',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		description: 'The encrypted card number from Adyen Web SDK',
		displayOptions: { show: { resource: ['checkout'], operation: ['createPayment'], paymentMethodType: ['scheme'] } },
	},
	{
		displayName: 'Encrypted Expiry Month',
		name: 'encryptedExpiryMonth',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		description: 'The encrypted expiry month from Adyen Web SDK',
		displayOptions: { show: { resource: ['checkout'], operation: ['createPayment'], paymentMethodType: ['scheme'] } },
	},
	{
		displayName: 'Encrypted Expiry Year',
		name: 'encryptedExpiryYear',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		description: 'The encrypted expiry year from Adyen Web SDK',
		displayOptions: { show: { resource: ['checkout'], operation: ['createPayment'], paymentMethodType: ['scheme'] } },
	},
	{
		displayName: 'Encrypted Security Code',
		name: 'encryptedSecurityCode',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		description: 'The encrypted security code from Adyen Web SDK',
		displayOptions: { show: { resource: ['checkout'], operation: ['createPayment'], paymentMethodType: ['scheme'] } },
	},
	{
		displayName: 'Stored Payment Method ID',
		name: 'storedPaymentMethodId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the stored payment method',
		displayOptions: { show: { resource: ['checkout'], operation: ['createPayment'], paymentMethodType: ['storedPaymentMethod'] } },
	},
	{
		displayName: 'Details',
		name: 'details',
		type: 'json',
		required: true,
		default: '{}',
		description: 'The payment details to submit (JSON format)',
		displayOptions: { show: { resource: ['checkout'], operation: ['submitDetails'] } },
	},
	{
		displayName: 'Payment Data',
		name: 'paymentData',
		type: 'string',
		required: false,
		default: '',
		description: 'The paymentData value from the previous response',
		displayOptions: { show: { resource: ['checkout'], operation: ['submitDetails'] } },
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['checkout'], operation: ['createSession', 'createPayment', 'getPaymentMethods'] } },
		options: [
			{ displayName: 'Country Code', name: 'countryCode', type: 'string', default: '', description: 'The two-character country code' },
			{ displayName: 'Shopper Email', name: 'shopperEmail', type: 'string', default: '', description: 'The shopper\'s email address' },
			{ displayName: 'Shopper Reference', name: 'shopperReference', type: 'string', default: '', description: 'Your unique identifier for the shopper' },
			{ displayName: 'Shopper Locale', name: 'shopperLocale', type: 'string', default: '', description: 'The locale for the shopper (e.g., en-US)' },
			{ displayName: 'Channel', name: 'channel', type: 'options', options: [{ name: 'Web', value: 'Web' }, { name: 'iOS', value: 'iOS' }, { name: 'Android', value: 'Android' }], default: 'Web', description: 'The platform where the payment takes place' },
			{ displayName: 'Store Payment Method', name: 'storePaymentMethod', type: 'boolean', default: false, description: 'Whether to store the payment method for future use' },
			{ displayName: 'Origin', name: 'origin', type: 'string', default: '', description: 'The origin URL of your application' },
		],
	},
];
